# export NO_MKDOCS_2_WARNING=1
site_name: Moviebox-API Documentation
repo_url: https://github.com/Simatwa/moviebox-api
repo_name: Moviebox-API
edit_uri: edit/main/docs/

nav:
  - Home: index.md

  - Guide:
      - Installation: installation.md
      - V1:
        - Introduction: v1/introduction.md
        - Movies: v1/movies.md
        - TV-Series: v1/tv_series.md
        - Commandline: v1/cli.md

      - V2:
        - Introduction: v2/introduction.md
        - Movies: v2/movies.md
        - TV-Series: v2/tv_series.md
        - Commandline: v2/cli.md

      - V3:
        - Introduction: v3/introduction.md
        - Movies: v3/movies.md
        - TV-Series: v3/tv_series.md
        - Commandline: v3/cli.md
  
  - Misc: miscellaneous.md


  - Blog:
    - blog/index.md

markdown_extensions:
  - abbr
  - tables
  - admonition
  - pymdownx.details
  - codehilite
  - attr_list
  - md_in_html

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
    
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences

    # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  
  - toc:
      permalink: true


plugins:
  - search
  - offline # offline build
  - blog:
      authors_profiles: true

theme:
  name: material
  #logo: assets/logo.png

  #favicon: images/favicon.png

  palette:

    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
      primary: teal

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: teal

  features:
    #- navigation.tabs
    # - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    # - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
  # - header.autohide
    - content.code.select
    - content.code.annotate
    - content.tooltips
  # editing & viewing source
    - content.action.edit
    - content.action.view

extra:
  generator: true # made with mkdocs
  #homepage: https://example.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Simatwa

    - icon: fontawesome/solid/paper-plane
      link: mailto:smartwacaleb@gmail.com

copyright: Copyright &copy; 2025 - 2026 Simatwa